const tg=window.Telegram.WebApp; tg.ready(); tg.expand();
let cart=[];
const el=id=>document.getElementById(id);
const categoriesSection=el('categoriesSection'), productsSection=el('productsSection'), categoriesElement=el('categories'), productsElement=el('products'), categoryTitle=el('categoryTitle'), cartPage=el('cartPage'), checkoutPage=el('checkoutPage'), cartElement=el('cart'), cartButton=el('cartButton'), cartCount=el('cartCount'), totalElement=el('total');

async function loadCategories(){
 try{const r=await fetch('/api/categories');const cats=await r.json();categoriesElement.innerHTML='';cats.forEach(c=>{const b=document.createElement('button');b.className='category';b.innerHTML=`${c.image?`<img class="category-image" src="${c.image}" alt="">`:''}<span class="category-overlay"></span><span class="category-name">${esc(c.name)}</span>`;b.onclick=()=>loadProducts(c.id,c.name);categoriesElement.appendChild(b)})}catch(e){categoriesElement.innerHTML='<p>Не удалось загрузить категории.</p>'}}
async function loadProducts(id,name){categoriesSection.classList.add('hidden');productsSection.classList.remove('hidden');cartPage.classList.add('hidden');checkoutPage.classList.add('hidden');categoryTitle.textContent=name;try{const r=await fetch(`/api/products?category_id=${id}`);const products=await r.json();productsElement.innerHTML='';if(!products.length){productsElement.innerHTML='<p>Товаров пока нет.</p>';return}products.forEach(p=>{const d=document.createElement('div');d.className='product';d.innerHTML=`${p.image?`<img src="${p.image}" alt="">`:''}<div class="product-content"><h3>${esc(p.name)}</h3><p class="description">${esc(p.description||'')}</p><div class="price">${Number(p.price).toFixed(2)} ₽</div><button class="add-button">Добавить в корзину</button></div>`;d.querySelector('.add-button').onclick=()=>addToCart(p);productsElement.appendChild(d)})}catch(e){productsElement.innerHTML='<p>Не удалось загрузить товары.</p>'}}
function addToCart(p){const x=cart.find(i=>i.id===p.id);if(x)x.quantity++;else cart.push({id:p.id,name:p.name,price:Number(p.price),quantity:1});updateCart();if(tg.HapticFeedback)tg.HapticFeedback.impactOccurred('light')}
function changeQuantity(id,delta){const x=cart.find(i=>i.id===id);if(!x)return;x.quantity+=delta;if(x.quantity<=0)cart=cart.filter(i=>i.id!==id);updateCart()}
function updateCart(){const count=cart.reduce((s,i)=>s+i.quantity,0);cartCount.textContent=count;cartButton.classList.toggle('hidden',count===0);renderCart()}
function renderCart(){if(!cart.length){cartElement.innerHTML='<p>Корзина пустая.</p>';totalElement.textContent='0 ₽';return}let total=0;cartElement.innerHTML='';cart.forEach(i=>{total+=i.price*i.quantity;const d=document.createElement('div');d.className='cart-item';d.innerHTML=`<div><strong>${esc(i.name)}</strong><div>${i.price.toFixed(2)} ₽</div></div><div class="quantity"><button>−</button><span>${i.quantity}</span><button>+</button></div>`;const bs=d.querySelectorAll('button');bs[0].onclick=()=>changeQuantity(i.id,-1);bs[1].onclick=()=>changeQuantity(i.id,1);cartElement.appendChild(d)});totalElement.textContent=`${total.toFixed(2)} ₽`}
function openCart(){categoriesSection.classList.add('hidden');productsSection.classList.add('hidden');checkoutPage.classList.add('hidden');cartPage.classList.remove('hidden');scrollTop()}
function showCategories(){productsSection.classList.add('hidden');cartPage.classList.add('hidden');checkoutPage.classList.add('hidden');categoriesSection.classList.remove('hidden');scrollTop()}
function checkout(){if(!cart.length){tg.showAlert('Корзина пустая');return}cartPage.classList.add('hidden');checkoutPage.classList.remove('hidden');scrollTop()}
async function sendOrder(){if(!cart.length)return;const delivery=el('delivery').value;const user=tg.initDataUnsafe?.user||{};try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user,items:cart,delivery})});const data=await r.json();if(!r.ok||!data.ok){tg.showAlert(data.error||'Ошибка создания заказа');return}cart=[];updateCart();tg.showPopup({title:'Заказ оформлен',message:`Номер заказа: #${data.order_id}`,buttons:[{type:'ok'}]});showCategories()}catch(e){tg.showAlert('Не удалось отправить заказ')}}
function scrollTop(){window.scrollTo({top:0,behavior:'smooth'})}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
loadCategories();updateCart();
